### ISSUE TITLE
Update the EBS to the new start_game structure

### ISSUE THREAD

**Issue by beheh** [HearthSim/twitch-hdt-ebs#14]
Refs HearthSim/hdt-internal#43.

**Comment by azeier** [comment]
[New data structure](https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/b6f56c557868c3026c56e2824fdffe6e31bfe381/Hearthstone%20Deck%20Tracker/Live/Data/BoardState.cs#L8-L21) with [payload version 3](https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/b6f56c557868c3026c56e2824fdffe6e31bfe381/Hearthstone%20Deck%20Tracker/Live/Data/Payload.cs#L16)
